[profile.default]
src = "src"
out = "out"
libs = ["lib"]
ast = true
solc = "0.8.10"
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[rpc_endpoints]
mainnet = "https://eth-mainnet.g.alchemy.com/v2/P-x0L9coIqzuhfI091DXitR7BzYbABFA"
blast = "https://rpc.ankr.com/blast"
optimism = "https://optimism.llamarpc.com"
fantom = "https://rpc.ankr.com/fantom"
arbitrum = "https://rpc.ankr.com/arbitrum"
bsc = "https://bsc-mainnet.public.blastapi.io"
moonriver = "https://moonriver.public.blastapi.io"
gnosis = "https://rpc.ankr.com/gnosis"
Avalanche = "https://rpc.ankr.com/avalanche"
polygon = "https://rpc.ankr.com/polygon"
celo = "https://rpc.ankr.com/celo"
Base = "https://developer-access-mainnet.base.org"